---

- name: Write global bashrc
  copy: src=bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644

- name: Write skeleton .bashrc
  copy: "src=.bashrc dest=/etc/skel/.bashrc owner=root group=root mode=0644"

- name: Determine ssh user homedir
  shell: "getent passwd {{ item }} | cut -d: -f6"
  register: bashrc_homedirs
  with_items: "{{ bashrc_users }}"
  changed_when: False

- name: Write ssh user homedir .bashrc
  copy: "src=.bashrc dest={{ item.stdout }}/.bashrc owner={{ item.item }} group={{ item.item }} mode=0644"
  with_items: "{{ bashrc_homedirs.results }}"

- name: Write root .bashrc
  copy: "src=root.bashrc dest=/root/.bashrc owner=root group=root mode=0644"
