---

- name: Write global bashrc
  ansible.builtin.copy:
    src: bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: '0644'

- name: Write skeleton .bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: '0644'

- name: Write root .bashrc
  ansible.builtin.copy:
    src: root.bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0644'
